# Generated by Django 4.2.1 on 2024-07-08 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('suitable_for', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExercisePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('suitable_for', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='healthrecommendation',
            name='diet_recommendations',
        ),
        migrations.RemoveField(
            model_name='healthrecommendation',
            name='exercise_recommendations',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('lightly_active', 'Lightly Active'), ('moderately_active', 'Moderately Active'), ('very_active', 'Very Active'), ('super_active', 'Super Active')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dietary_preferences',
            field=models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('pescatarian', 'Pescatarian'), ('gluten_free', 'Gluten-Free'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('low_carb', 'Low-Carb'), ('high_protein', 'High-Protein'), ('diabetic_friendly', 'Diabetic-Friendly'), ('low_sodium', 'Low-Sodium'), ('allergies', 'Allergies')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_conditions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='healthrecommendation',
            name='diet_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.dietplan'),
        ),
        migrations.AddField(
            model_name='healthrecommendation',
            name='exercise_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.exerciseplan'),
        ),
    ]
