# Generated by Django 5.0.7 on 2024-07-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_preferences',
            field=models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten_free', 'Gluten-Free'), ('low_carb', 'Low-Carb'), ('high_protein', 'High-Protein'), ('diabetic_friendly', 'Diabetic-Friendly'), ('allergies', 'Allergies')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='health_conditions',
            field=models.TextField(choices=[('hypertension', 'hypertension'), ('diabetes', 'diabetes'), ('asthma', 'asthma'), ('heart_disease', 'heart_disease'), ('allergy', 'allergy'), ('thyroid', 'thyroid'), ('cancer', 'cancer'), ('kidney_disease', 'kidney_disease')], null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='medical_history',
            field=models.TextField(blank=True, choices=[('previous_surgeries', 'previous_surgeries'), ('chronic_illnesses', 'chronic_illnesses'), ('medications', 'medications'), ('allergies', 'allergies')], null=True),
        ),
    ]
