# Generated by Django 5.0.6 on 2024-07-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
