# Generated by Django 5.0.6 on 2024-07-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_emailreminder_send_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailreminder',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
