# Generated by Django 5.0.6 on 2024-08-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_reminder_delete_emailreminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseReminder',
        ),
    ]
