# Generated by Django 5.0.7 on 2024-08-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_user_is_superuser'),
        ('user', '0016_emailreminder_exercisereminder_delete_reminder'),
    ]

    operations = [
    ]
