# Generated by Django 5.0.7 on 2024-08-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_merge_20240805_1452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseReminder',
        ),
    ]
