<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-08-06 10:22
=======
# Generated by Django 5.0.7 on 2024-08-06 09:47
>>>>>>> a6df0f0e56e2076e120663c948ff6b6d90900aaf

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_merge_20240805_1452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseReminder',
        ),
    ]
