# Generated by Django 5.0.7 on 2024-08-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
