# Generated by Django 5.0.7 on 2024-08-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_delete_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalfile',
            name='file',
            field=models.FileField(upload_to='media/medical_files/'),
        ),
    ]
