# Generated by Django 5.0.7 on 2024-08-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_medicalfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalfile',
            name='file',
            field=models.FileField(upload_to='medical_files/'),
        ),
    ]
