# Generated by Django 5.0.7 on 2024-08-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_userfile_delete_medicalfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFile',
        ),
    ]
