# Generated by Django 5.0.7 on 2024-08-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_medicalfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalFile',
        ),
    ]
