# Generated by Django 5.0.7 on 2024-08-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_remove_appointment_time_slot_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='BookedSlot',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
