# Generated by Django 5.0.7 on 2024-08-21 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_userprofile_blood_pressure_userprofile_heart_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='heart_rate',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='step_count',
        ),
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heart_rate', models.IntegerField()),
                ('systolic', models.IntegerField()),
                ('diastolic', models.IntegerField()),
                ('steps', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
