# Generated by Django 5.0.7 on 2024-09-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
