# Generated by Django 5.0.7 on 2024-09-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_remove_doctor_location_remove_doctor_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
    ]
