# Generated by Django 5.0.7 on 2024-09-11 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_doctor_location_doctor_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='reviews',
        ),
    ]
