# Generated by Django 5.0.7 on 2024-09-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthreport',
            name='report_file',
            field=models.FileField(upload_to='reports/'),
        ),
    ]
